project:
  type: website
  output-dir: docs

website:
  title: "BioEngineering Statistics Winter 2026"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - Syllabus.qmd
      - Policies.qmd
      - Schedule.qmd
      - Lectures.qmd
      - Homework.qmd
      - Software.qmd
      - Resources.qmd

format:
  html:
    theme: cerulean
    css: styles.css
    toc: true
    embed-resources: true

editor: visual

